---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Karsten Schuldt (Text)"
- "Rudolf Mumenthaler (Bild)"
title: "Der Blick zweier Disziplinen auf eine Bibliothek"
date: 2015-12-12 13:00
comments: false
sharing: true
footer: true

---