---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Ute Engelkenmeier"
title: "Das Bild der Bibliothek und Bibliothekare in den Fernsehgenres Comedy und Komödie"
date: 2015-12-12 13:00
abstract: "Mittels der empirischen Methode der standardisierten, quantitativen
Inhaltsanalyse werden 51 Fernsehsendungen aus den Subgenres Comedy und
Komödie untersucht, in welchen Bibliotheken als Schauplatz und
Bibliothekare als Figur vorkommen. Der betrachtete Zeitraum der
Ausstrahlungen ist von Januar 2010 bis Juli 2015. Ziel der Untersuchung
ist die Klärung der Frage, ob Bibliotheken und Bibliothekare stereotyp
dargestellt werden und ob sie innerhalb der gewählten Subgenres Objekt
des Witzes sind. Untersucht werden unter anderem die Dimensionen
Erscheinungsbild und Nutzungsmotive. Die Untersuchung kommt zu dem
Schluss, dass das Erscheinungsbild von Bibliotheken überwiegend auf das
konstitutive Element der Bücherregale reduziert ist. In der Nutzung
überwiegen Motive wie Ausleihen, Lesen, aber auch Nutzung der Bibliothek
als sozialer Treffpunkt (Kennenlernen, Date) oder die Suche nach einem
ruhigen Rückzugsort. Das Bild der Bibliothekare ist im äußeren
Erscheinungsbild zwar konservativer als andere Figuren, jedoch nicht
negativ, auch sind die Rollen nicht Objekt des Witzes. Eine Tendenz zu
einer weniger konservativen Darstellung in jüngeren Produktionen ist
festzustellen."
comments: false
sharing: true
footer: true

---