---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Tina Zürn"
title: "Gebaute Signatur: Die Seattle Public Library von Rem Koolhaas"
abstract: "Dass sich der Leser im Freihandmagazin einer Bibliothek heute selbst mit
Büchern versorgen kann, ist das Ergebnis eines langwierigen Prozesses
der sukzessiven Öffnung, die in den USA begonnen hat. Seither entfallen
Umwege und Wartezeiten bei der Buchausgabe aus dem geschlossenen
Magazin. Doch inwiefern verändert der unmittelbare Zugriff auf das Buch
die Bewegungsabläufe in der Bibliotheksarchitektur? Die 2004
fertiggestellte Seattle Public Library des Office for Metropolitan
Architecture (OMA) verleiht der Suchbewegung zwischen den Beständen
erstmals eine adäquate architektonische Struktur. Im Handmagazin der
Stadtbibliothek verbinden sich Signatur und Wegführung –
bibliothekarische und architektonische Lenkung des Lesers – zu einem
einheitlichen Leitsystem."
date: 2015-12-12 17:00
comments: false
sharing: true
footer: true

---