---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Hans-Christoph Hobohm"
title: "Vom Ort zum Akteur. Heterotopologie + Akteur-Network-Theorie auf die Bibliothek bezogen"
date: 2015-12-15 13:00
comments: false
sharing: true
footer: true

---