---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #28: Das Bild der Bibliothek"
subtitle: ""
date: 2015-12-15 18:00
comments: false
sharing: true
footer: true

---
