---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Frank Hartmann"
title: "Dokumentation als Gegenidee zur Bibliothek"
abstract: "Schon zur Wende ins 20. Jahrhundert zweifelte der belgische Privatgelehrte Paul Otlet an der Zukunft des Buches und der Bibliothek. Statt dessen begann er damit, eine Dokumentation und euorganisation des Weltwissens anzulegen, und mittels eines Karteikartensystems (Répertoire Bibliographique Universel) zu vernetzen. Dieses Projekt eines flexiblen, abfrageorientierten Wissensbestandes in einem 'Hypermedium' (Otlet) besetzte jene technologische Leerstelle, die inzwischen eine die bibliothekarische Epoche aufsprengende neue Wissenskultur der digitalen Medialität produziert hat."
date: 2015-12-09 20:00
comments: false
sharing: true
footer: true

---