---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Sandra Balck"
title: "Das LIBREAS Symposium: Ein Erfahrungsbericht"
date: 2015-12-27 13:00
comments: false
sharing: true
footer: true

---