---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Kirsten Wagner"
title: "Die architektonische Idee der modernen Bibliothek"
abstract: "Die moderne Bibliothek geht auf einen Übergang der Saalbibliothek zur 
Magazinbibliothek zurück, der sich im 19. Jahrhundert vollzieht. Bevor
erste Magazinbibliotheken ab den 1850er Jahren gebaut werden, existiert
die moderne Bibliothek in der ersten Hälfte des 19. Jahrhunderts vor
allem als Idee. Es entsteht eine kaum übersehbare Zahl an
Bibliotheksentwürfen und -schriften, in denen nach einer
architektonischen Form gesucht wird, die der Expansion der
Gutenberggalaxis, der Erweiterung des Nutzerkreises und der räumlichen
Ausdifferenzierung der Bibliotheksfunktionen gerecht wird. Ausgehend von
der öffentlichen Bibliotheksdiskussion, wie sie auch und besonders in
der Architekturpresse geführt wird, untersucht der Beitrag am Beispiel
der französischen *Bibliothèque royale* den Entwurf der modernen
Bibliothek als Zentral- bzw. Rundbau mit einem Lesesaal in seiner Mitte.
In diesen Entwurf schreiben sich in der Zeitspanne von 1790 bis 1840
vollkommen verschiedene Wissens- und Körperordnungen ein. Ihre
Verbindung besteht dort, wo das absolute räumliche Zentrum der
Bibliothek mit einem allsehenden Auge besetzt zu sein scheint."
date: 2015-12-12 13:00
comments: false
sharing: true
footer: true

---