---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Kirsten Wagner"
title: "Die architektonische Idee der modernen Bibliothek"
abstract: "Die moderne Bibliothek geht auf einen Übergang der Saalbibliothek zur
Magazinbibliothek zurück, der sich im 19. Jahrhundert vollzog. Bevor
erste Magazinbibliotheken ab den 1850er Jahren gebaut wurden, existierte
die moderne Bibliothek in der ersten Hälfte des 19. Jahrhunderts vor
allem als Idee. Es entstand eine kaum übersehbare Zahl an
Bibliotheksentwürfen und -schriften, in denen nach einer
architektonischen Form gesucht wurde, die der Expansion der
Gutenberggalaxis, der Erweiterung des Nutzerkreises und der räumlichen
Ausdifferenzierung der Bibliotheksfunktionen entsprach. Ausgehend von
der öffentlichen Bibliotheksdiskussion, wie sie auch und besonders in
der Architekturpresse geführt wurde, untersucht der Beitrag am Beispiel
der französischen *Bibliothèque royale* den Entwurf der modernen
Bibliothek als Zentral- bzw. Rundbau mit einem Lesesaal in seiner Mitte.
In diesen Entwurf schreiben sich in der Zeitspanne von 1790 bis 1850
vollkommen verschiedene Wissens- und Körperordnungen ein. Ihre
Verbindung besteht dort, wo sich das absolute räumliche Zentrum der
Bibliothek durch ein allsehendes Auge besetzt zeigt."
date: 2015-12-12 13:00
comments: false
sharing: true
footer: true

---