---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Nathalie Vallet"
- "Inge Somers"
- "Michel Corthaut" 
- "Helga Spaey"
- "Arjaan De Feyter"
- "Johan Praet"
title: "Embracing changes or struggling with stereotypes? The awareness of changing images of Flemish public libraries by students in interior architecture"
date: 2015-12-12 17:00
comments: false
sharing: true
footer: true

---