---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Michael Weller"
title: "Rezension zu: Hartmann, Thomas: Urheberrecht für die Bildungspraxis. Bielefeld: W. Bertelsmann Verlag, 2014."
date: 2015-12-12 17:00
comments: false
sharing: true
footer: true

---