---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "28"
year: "2015"
contributor: 
- "Karin Aleksander"
title: "Ist eine transdisziplinäre Bibliothek möglich? Oder: Wie die Geschlechterforschung Idee und Ideal der Bibliothek herausfordert"
date: 2015-12-09 20:00
comments: false
sharing: true
footer: true

---